# Generated by Django 4.1.4 on 2023-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_person_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='static/img/people'),
        ),
    ]
