# Generated by Django 4.1.4 on 2023-06-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_person_contact_info_alter_person_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
